image: docker.io/python:3.12-bookworm

before_script:
  - git clone https://gitlab.com/librecube/lib/python-cfdp.git
  - pushd python-cfdp; pip install cfdp; popd

build-job:
  stage: build
  script:
    - make all
  artifacts:
    paths:
      - build/

test-job1:
  stage: test
  script:
    - make test