#ifndef CONSTANTS_H
#define CONSTANTS_H

#include "dataview.h"

enum MachineState {
	SEND_METADATA,
	SEND_FILE,
	SEND_EOF,
	TRANSACTION_CANCELLED,
	WAIT_FOR_MD,
	WAIT_FOR_EOF,
	GET_MISSING_DATA,
	SEND_FINISHED,
	COMPLETED
};

enum FaultHandlerAction {
	FAULT_HANDLER_CANCEL,
    FAULT_HANDLER_SUSPEND,
    FAULT_HANDLER_IGNORE,
    FAULT_HANDLER_ABANDON
};

#define DIRECTIVE_CODE_EOF 0x04
#define DIRECTIVE_CODE_FINISHED 0x05

#define MAX_FILE_NAME_SIZE (cfdpFileName_REQUIRED_BYTES_FOR_ACN_ENCODING - 1)
#define MAX_NUMBER_OF_SENDER_MACHINES 1
#define MAX_NUMBER_OF_RECEIVER_MACHINES 1

#define FILE_SEGMENT_LEN (cfdpFileData_REQUIRED_BYTES_FOR_ACN_ENCODING - 1)
#define INACTIVITY_TIMEOUT 30
#define ACK_TIMER_LIMIT 5
#define ACK_TIMER_EXPIRATION_LIMIT 3
#define NAK_TIMER_INTERVAL 5
#define NAK_TIMER_EXPIRATION_LIMIT 5

extern const enum FaultHandlerAction DEFAULT_FAULT_HANDLER_ACTIONS [16];

#endif